{% set version = "1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-icebox
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ICEbox_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ICEbox/ICEbox_{{ version }}.tar.gz
  sha256: df796c6e0a771b96c124e2a5ae841064ebd3a026615e9447d739040cc36555b3

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib('c') }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib('m2w64_c') }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-checkmate
    - r-data.table
    - r-ggplot2
  run:
    - r-base
    - r-rcpp
    - r-checkmate
    - r-data.table
    - r-ggplot2

test:
  commands:
    - $R -e "library('ICEbox')"           # [not win]
    - "\"%R%\" -e \"library('ICEbox')\""  # [win]

about:
  home: https://github.com/kapelner/ICEbox
  license: GPL-2.0-only OR GPL-3.0-only
  summary: Implements Individual Conditional Expectation (ICE) plots, a tool for visualizing the model estimated by any supervised learning algorithm. ICE plots refine Friedman's partial dependence plot by graphing the functional relationship between the predicted response and a covariate of interest for individual observations.
    Specifically, ICE plots highlight the variation in the fitted values across the range of a covariate of interest, suggesting where and to what extent they may exist.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: ICEbox
# Type: Package
# Title: Individual Conditional Expectation Plot Toolbox
# Version: 1.1.5
# Date: 2022-08-18
# Author: Alex Goldstein, Adam Kapelner, Justin Bleich
# Maintainer: Adam Kapelner <kapelner@qc.cuny.edu>
# Description: Implements Individual Conditional Expectation (ICE) plots, a tool for visualizing the model estimated by any supervised learning algorithm. ICE plots refine Friedman's partial dependence plot by graphing the functional relationship between the predicted response and a covariate of interest for individual observations. Specifically, ICE plots highlight the variation in the fitted values across the range of a covariate of interest, suggesting where and to what extent they may exist.
# License: GPL-2 | GPL-3
# Depends: sfsmisc
# Suggests: randomForest, MASS
# NeedsCompilation: no
# Packaged: 2022-08-22 14:00:12 UTC; kapel
# Repository: CRAN
# Date/Publication: 2022-08-22 14:20:10 UTC
